# Generated by Django 4.2.7 on 2023-11-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_newuser_confirmation_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=1000)),
            ],
        ),
    ]
