# Generated by Django 4.2.6 on 2023-11-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_newuser_is_active_newuser_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_img', models.ImageField(upload_to='Files/Teams/')),
                ('dev_name', models.CharField(max_length=100)),
                ('dev_role', models.CharField(max_length=50)),
                ('dev_description', models.CharField(max_length=300)),
            ],
        ),
    ]
