# Generated by Django 4.2.6 on 2023-11-12 12:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_message_alter_about_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='newuser',
            name='userid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
