# Generated by Django 4.2.6 on 2023-11-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_newuser_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='bio',
            field=models.CharField(default="Welcome to my profile! I'm a passionate individual with diverse interests and talents. Join me on my journey and let's explore the world together.", max_length=200),
        ),
    ]
