# Generated by Django 4.2.6 on 2023-11-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_loanrequest_donationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequest',
            name='transaction_happen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='transaction_happen',
            field=models.BooleanField(default=False),
        ),
    ]
