# Generated by Django 4.2.7 on 2023-11-27 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='email',
        ),
        migrations.RemoveField(
            model_name='message',
            name='name',
        ),
        migrations.AddField(
            model_name='message',
            name='userr',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='main.newuser'),
        ),
        migrations.AlterField(
            model_name='message',
            name='comment',
            field=models.TextField(default='null', max_length=300, null=True),
        ),
    ]
