# Generated by Django 4.2.7 on 2023-11-27 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_message_email_remove_message_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='message',
            table='message',
        ),
    ]
