# Generated by Django 4.2.6 on 2023-12-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_addbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='addbalance',
            name='is_first_transaction',
            field=models.BooleanField(default=False),
        ),
    ]
