# Generated by Django 4.2.6 on 2023-12-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_addbalance_is_first_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbalance',
            name='available_balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='addbalance',
            name='is_first_transaction',
            field=models.BooleanField(default=True),
        ),
    ]
