# Generated by Django 4.2.6 on 2023-12-04 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_addbalance_available_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendDonation',
            fields=[
                ('donation_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField(default=0.0)),
                ('wish', models.CharField(max_length=200)),
                ('donated_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations_received', to='main.newuser')),
                ('donated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations_made', to='main.newuser')),
                ('donation_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='main.donationrequest')),
            ],
        ),
    ]
