# Generated by Django 4.2.6 on 2023-12-09 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_rename_senddonation_adddonation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_at', models.DateTimeField(auto_now_add=True)),
                ('report_reason', models.CharField(max_length=50)),
                ('short_description', models.CharField(max_length=200)),
                ('report_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_sent', to='main.newuser')),
                ('report_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to='main.newuser')),
            ],
        ),
    ]
